version: "3.9"

services:
  gescon:
    image: julianases2014/gescon_ci:master
    container_name: frontend_gescon
    networks:
      - compose-bridge
    ports:
      - 8080:80
  mongodb:
    image: mongo:latest
    container_name: meu-mongo
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: "bridge"
