name: Node

on:
  push:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14.x, 16.x, 18.x]
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
            steps:
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

      
#    - name: Build
#      run: docker-compose build
 
#  docker:
#    needs: build
#    uses: ./.github/workflows/Docker.yml
