name: Node

on:
  push:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [16.x, 18.x]
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci && npm i @angular/cli && npm i json-server
    - run: docker compose build

