name: Node

on:
  push:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [16.x, 18.x]
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm test
  docker:
    needs: test
    uses: './.github/workflows/Docker.yml'
#    - name: BD-Json-server
#      run: cd backend && ng serve

 #   - name: Build-DB
 #     run: docker-compose build


      
#    - name: Build
#      run: docker-compose build
 
#  docker:
#    needs: build
#    uses: ./.github/workflows/Docker.yml

#    - name: Build-DB
#      run: docker-compose build

#    - name: Create-DB
#      run: docker-compose up -d

#    - name: Test
#      run: go test -v main_test.go 


