name: Node

on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [16.x, 18.x]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Rodando o npm install
        run: npm install --silent

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rodando o npm install
        run: npm install --silent

      - name: Fazendo o Build
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: programa
          path: dist

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  teste_img_docker:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo o pull da imagem
        run: docker pull julianases2014/gescon_ci:master

      - name: Rodando a imagem criada
        run: docker run -d --name node-container julianases2014/gescon_ci:master

      - name: Listando os containers rodando
        run: docker ps
        
      - name: Inspecionando o container criado
        run: docker inspect node-container
